DEFENDERS = {
    "Denari": {
        "gender": "male",
        "role": ["anti-entry", "crowd-control"],
        "side": "defender",
        "speed": 3,
        "country": "switzerland",
        "continent": "europe",
        "org": "unaffiliated",
        "squad": "nighthaven",
        "year": "2025",
    },
    "Skopos": {
        "gender": "female",
        "role": ["intel", "support"],
        "side": "defender",
        "speed": 2,
        "country": "greece",
        "continent": "europe",
        "org": "ekam",
        "squad": "wolfguard",
        "year": "2024",
    },
    "Sentry": {
        "gender": "male",
        "role": ["support"],
        "side": "defender",
        "speed": 2,
        "country": "undefined",
        "continent": "none",
        "org": "rainbow operation staff",
        "squad": "none",
        "year": "2024",
    },
    "Tubarao": {
        "gender": "male",
        "role": ["anti-gadget", "crowd-control"],
        "side": "defender",
        "speed": 2,
        "country": "portugal",
        "continent": "europe",
        "org": "dae",
        "squad": "wolfguard",
        "year": "2023",
    },
    "Fenrir": {
        "gender": "male",
        "role": ["trapper", "crowd-control"],
        "side": "defender",
        "speed": 2,
        "country": "sweden",
        "continent": "europe",
        "org": "unaffiliated",
        "squad": "redhammer",
        "year": "2023",
    },
    "Solis": {
        "gender": "female",
        "role": ["intel", "support"],
        "side": "defender",
        "speed": 2,
        "country": "colombia",
        "continent": "south america",
        "org": "afeau",
        "squad": "ghosteyes",
        "year": "2022",
    },
    "Azami": {
        "gender": "female",
        "role": ["anti-entry", "support"],
        "side": "defender",
        "speed": 2,
        "country": "japan",
        "continent": "asia",
        "org": "unaffiliated",
        "squad": "viperstrike",
        "year": "2022",
    },
    "Thorn": {
        "gender": "female",
        "role": ["anti-entry", "trapper"],
        "side": "defender",
        "speed": 2,
        "country": "ireland",
        "continent": "europe",
        "org": "emergency response unit",
        "squad": "redhammer",
        "year": "2021",
    },
    "Thunderbird": {
        "gender": "female",
        "role": ["support"],
        "side": "defender",
        "speed": 2,
        "country": "canada",
        "continent": "north america",
        "org": "star-net aviation",
        "squad": "wolfguard",
        "year": "2021",
    },
    "Aruni": {
        "gender": "female",
        "role": ["anti-entry", "anti-gadget"],
        "side": "defender",
        "speed": 1,
        "country": "thailand",
        "continent": "asia",
        "org": "nighthaven",
        "squad": "nighthaven",
        "year": "2020",
    },
    "Melusi": {
        "gender": "female",
        "role": ["intel", "crowd-control"],
        "side": "defender",
        "speed": 1,
        "country": "south africa",
        "continent": "africa",
        "org": "inkaba task force",
        "squad": "wolfguard",
        "year": "2020",
    },
    "Oryx": {
        "gender": "male",
        "role": ["support"],
        "side": "defender",
        "speed": 2,
        "country": "jordan",
        "continent": "africa",
        "org": "unaffiliated",
        "squad": "redhammer",
        "year": "2020",
    },
    "Wamai": {
        "gender": "male",
        "role": ["anti-gadget", "trapper"],
        "side": "defender",
        "speed": 2,
        "country": "kenya",
        "continent": "africa",
        "org": "nighthaven",
        "squad": "nighthaven",
        "year": "2019",
    },
    "Goyo": {
        "gender": "male",
        "role": ["anti-entry", "trapper"],
        "side": "defender",
        "speed": 2,
        "country": "mexico",
        "continent": "north america",
        "org": "fuerzas especiales",
        "squad": "redhammer",
        "year": "2019",
    },
    "Warden": {
        "gender": "male",
        "role": ["anti-gadget", "intel"],
        "side": "defender",
        "speed": 1,
        "country": "usa",
        "continent": "north america",
        "org": "secret service",
        "squad": "ghosteyes",
        "year": "2019",
    },
    "Mozzie": {
        "gender": "male",
        "role": ["anti-gadget", "intel"],
        "side": "defender",
        "speed": 2,
        "country": "australia",
        "continent": "oceania",
        "org": "sasr",
        "squad": "ghosteyes",
        "year": "2019",
    },
    "Kaid": {
        "gender": "male",
        "role": ["anti-entry", "anti-gadget"],
        "side": "defender",
        "speed": 1,
        "country": "morocco",
        "continent": "africa",
        "org": "gigr",
        "squad": "redhammer",
        "year": "2018",
    },
    "Clash": {
        "gender": "female",
        "role": ["intel", "crowd-control"],
        "side": "defender",
        "speed": 1,
        "country": "england",
        "continent": "europe",
        "org": "gsutr",
        "squad": "wolfguard",
        "year": "2018",
    },
    "Maestro": {
        "gender": "male",
        "role": ["anti-gadget", "intel"],
        "side": "defender",
        "speed": 1,
        "country": "italy",
        "continent": "europe",
        "org": "gis",
        "squad": "viperstrike",
        "year": "2018",
    },
    "Alibi": {
        "gender": "female",
        "role": ["trapper", "intel"],
        "side": "defender",
        "speed": 3,
        "country": "libya",
        "continent": "africa",
        "org": "gis",
        "squad": "viperstrike",
        "year": "2018",
    },
    "Vigil": {
        "gender": "male",
        "role": ["anti-gadget", "crowd-control"],
        "side": "defender",
        "speed": 3,
        "country": "redacted",
        "continent": "none",
        "org": "707th smb",
        "squad": "ghosteyes",
        "year": "2017",
    },
    "Ela": {
        "gender": "female",
        "role": ["trapper", "crowd-control"],
        "side": "defender",
        "speed": 2,
        "country": "poland",
        "continent": "europe",
        "org": "grom",
        "squad": "nighthaven",
        "year": "2017",
    },
    "Lesion": {
        "gender": "male",
        "role": ["anti-entry", "trapper"],
        "side": "defender",
        "speed": 2,
        "country": "hong kong",
        "continent": "asia",
        "org": "sdu",
        "squad": "ghosteyes",
        "year": "2017",
    },
    "Mira": {
        "gender": "female",
        "role": ["intel", "support"],
        "side": "defender",
        "speed": 1,
        "country": "spain",
        "continent": "europe",
        "org": "geo",
        "squad": "viperstrike",
        "year": "2017",
    },
    "Echo": {
        "gender": "male",
        "role": ["intel", "crowd-control"],
        "side": "defender",
        "speed": 2,
        "country": "japan",
        "continent": "asia",
        "org": "sat",
        "squad": "viperstrike",
        "year": "2016",
    },
    "Caveira": {
        "gender": "female",
        "role": ["intel", "crowd-control"],
        "side": "defender",
        "speed": 3,
        "country": "brazil",
        "continent": "south america",
        "org": "bope",
        "squad": "ghosteyes",
        "year": "2016",
    },
    "Valkyrie": {
        "gender": "female",
        "role": ["intel", "support"],
        "side": "defender",
        "speed": 2,
        "country": "usa",
        "continent": "north america",
        "org": "navy seal",
        "squad": "ghosteyes",
        "year": "2016",
    },
    "Frost": {
        "gender": "female",
        "role": ["anti-entry", "trapper"],
        "side": "defender",
        "speed": 2,
        "country": "canada",
        "continent": "north america",
        "org": "jtf2",
        "squad": "wolfguard",
        "year": "2016",
    },
    "Mute": {
        "gender": "male",
        "role": ["anti-gadget", "crowd-control"],
        "side": "defender",
        "speed": 2,
        "country": "england",
        "continent": "europe",
        "org": "sas",
        "squad": "viperstrike",
        "year": "2015",
    },
    "Smoke": {
        "gender": "male",
        "role": ["anti-entry", "trapper"],
        "side": "defender",
        "speed": 2,
        "country": "england",
        "continent": "europe",
        "org": "sas",
        "squad": "nighthaven",
        "year": "2015",
    },
    "Castle": {
        "gender": "male",
        "role": ["anti-entry", "support"],
        "side": "defender",
        "speed": 2,
        "country": "usa",
        "continent": "europe",
        "org": "fbi swat",
        "squad": "wolfguard",
        "year": "2015",
    },
    "Pulse": {
        "gender": "male",
        "role": ["intel", "support"],
        "side": "defender",
        "speed": 3,
        "country": "usa",
        "continent": "north america",
        "org": "fbi swat",
        "squad": "nighthaven",
        "year": "2015",
    },
    "Doc": {
        "gender": "male",
        "role": ["support"],
        "side": "defender",
        "speed": 1,
        "country": "france",
        "continent": "europe",
        "org": "gign",
        "squad": "wolfguard",
        "year": "2015",
    },
    "Rook": {
        "gender": "male",
        "role": ["support"],
        "side": "defender",
        "speed": 1,
        "country": "france",
        "continent": "europe",
        "org": "gign",
        "squad": "viperstrike",
        "year": "2015",
    },
    "Jager": {
        "gender": "male",
        "role": ["anti-gadget", "support"],
        "side": "defender",
        "speed": 2,
        "country": "germany",
        "continent": "europe",
        "org": "gsg 9",
        "squad": "viperstrike",
        "year": "2015",
    },
    "Bandit": {
        "gender": "male",
        "role": ["anti-entry", "anti-gadget"],
        "side": "defender",
        "speed": 3,
        "country": "germany",
        "continent": "europe",
        "org": "gsg 9",
        "squad": "wolfguard",
        "year": "2015",
    },
    "Tachanka": {
        "gender": "male",
        "role": ["anti-entry", "crowd-control"],
        "side": "defender",
        "speed": 1,
        "country": "russia",
        "continent": "europe",
        "org": "spetsnaz",
        "squad": "redhammer",
        "year": "2015",
    },
    "Kapkan": {
        "gender": "male",
        "role": ["anti-entry", "trapper"],
        "side": "defender",
        "speed": 2,
        "country": "russia",
        "continent": "europe",
        "org": "spetsnaz",
        "squad": "redhammer",
        "year": "2015",
    },
}

ATTACKERS = {
    "Rauora": {
        "gender": "female",
        "role": ["support", "map-control"],
        "side": "attacker",
        "speed": 2,
        "country": "new zealand",
        "continent": "oceania",
        "org": "ngati tumatauenga",
        "squad": "viperstrike",
        "year": "2025",
    },
    "Striker": {
        "gender": "female",
        "role": ["support"],
        "side": "attacker",
        "speed": 2,
        "country": "undefined",
        "continent": "none",
        "org": "rainbow operation staff",
        "squad": "none",
        "year": "2024",
    },
    "Deimos": {
        "gender": "male",
        "role": ["intel", "map-control"],
        "side": "attacker",
        "speed": 2,
        "country": "usa",
        "continent": "north america",
        "org": "keres legion",
        "squad": "none",
        "year": "2024",
    },
    "Ram": {
        "gender": "female",
        "role": ["anti-gadget", "breach"],
        "side": "attacker",
        "speed": 1,
        "country": "south korea",
        "continent": "asia",
        "org": "35th commando battalion",
        "squad": "redhammer",
        "year": "2023",
    },
    "Brava": {
        "gender": "female",
        "role": ["anti-gadget", "intel"],
        "side": "attacker",
        "speed": 3,
        "country": "brazil",
        "continent": "south america",
        "org": "cot",
        "squad": "viperstrike",
        "year": "2023",
    },
    "Grim": {
        "gender": "male",
        "role": ["front-line", "map-control"],
        "side": "attacker",
        "speed": 3,
        "country": "singapore",
        "continent": "asia",
        "org": "nighthaven",
        "squad": "nighthaven",
        "year": "2023",
    },
    "Sens": {
        "gender": "undefined",
        "role": ["support", "map-control"],
        "side": "attacker",
        "speed": 3,
        "country": "belgium",
        "continent": "europe",
        "org": "sfg",
        "squad": "wolfguard",
        "year": "2022",
    },
    "Osa": {
        "gender": "female",
        "role": ["intel", "support"],
        "side": "attacker",
        "speed": 1,
        "country": "croatia",
        "continent": "europe",
        "org": "nighthaven",
        "squad": "nighthaven",
        "year": "2021",
    },
    "Flores": {
        "gender": "male",
        "role": ["anti-gadget", "intel"],
        "side": "attacker",
        "speed": 2,
        "country": "argentina",
        "continent": "south america",
        "org": "unaffiliated",
        "squad": "ghosteyes",
        "year": "2021",
    },
    "Zero": {
        "gender": "male",
        "role": ["anti-gadget", "intel"],
        "side": "attacker",
        "speed": 3,
        "country": "usa",
        "continent": "north america",
        "org": "ros",
        "squad": "ghosteyes",
        "year": "2020",
    },
    "Ace": {
        "gender": "male",
        "role": ["anti-gadget", "breach"],
        "side": "attacker",
        "speed": 1,
        "country": "norway",
        "continent": "europe",
        "org": "nighthaven",
        "squad": "nighthaven",
        "year": "2020",
    },
    "Iana": {
        "gender": "female",
        "role": ["intel", "front-line"],
        "side": "attacker",
        "speed": 2,
        "country": "netherlands",
        "continent": "europe",
        "org": "reu",
        "squad": "ghosteyes",
        "year": "2020",
    },
    "Kali": {
        "gender": "female",
        "role": ["anti-gadget", "support"],
        "side": "attacker",
        "speed": 2,
        "country": "india",
        "continent": "asia",
        "org": "nighthaven",
        "squad": "nighthaven",
        "year": "2019",
    },
    "Amaru": {
        "gender": "male",
        "role": ["front-line", "map-control"],
        "side": "attacker",
        "speed": 2,
        "country": "peru",
        "continent": "south america",
        "org": "apca",
        "squad": "redhammer",
        "year": "2019",
    },
    "Nokk": {
        "gender": "female",
        "role": ["front-line", "map-control"],
        "side": "attacker",
        "speed": 2,
        "country": "redacted",
        "continent": "none",
        "org": "jaeger corps",
        "squad": "ghosteyes",
        "year": "2019",
    },
    "Gridlock": {
        "gender": "female",
        "role": ["support", "map-control"],
        "side": "attacker",
        "speed": 1,
        "country": "australia",
        "continent": "oceania",
        "org": "sasr",
        "squad": "redhammer",
        "year": "2019",
    },
    "Nomad": {
        "gender": "female",
        "role": ["front-line", "map-control"],
        "side": "attacker",
        "speed": 2,
        "country": "morocco",
        "continent": "africa",
        "org": "gigr",
        "squad": "wolfguard",
        "year": "2018",
    },
    "Maverick": {
        "gender": "male",
        "role": ["breach", "front-line"],
        "side": "attacker",
        "speed": 3,
        "country": "usa",
        "continent": "north america",
        "org": "gsutr",
        "squad": "ghosteyes",
        "year": "2018",
    },
    "Lion": {
        "gender": "male",
        "role": ["intel", "map-control"],
        "side": "attacker",
        "speed": 2,
        "country": "france",
        "continent": "europe",
        "org": "gbrn threat unit",
        "squad": "wolfguard",
        "year": "2018",
    },
    "Finka": {
        "gender": "female",
        "role": ["front-line", "support"],
        "side": "attacker",
        "speed": 2,
        "country": "belarus",
        "continent": "europe",
        "org": "gbrn threat unit",
        "squad": "nighthaven",
        "year": "2018",
    },
    "Dokkaebi": {
        "gender": "female",
        "role": ["intel", "map-control"],
        "side": "attacker",
        "speed": 3,
        "country": "south korea",
        "continent": "asia",
        "org": "707th smb",
        "squad": "viperstrike",
        "year": "2017",
    },
    "Zofia": {
        "gender": "female",
        "role": ["anti-gadget", "breach"],
        "side": "attacker",
        "speed": 1,
        "country": "poland",
        "continent": "europe",
        "org": "grom",
        "squad": "ghosteyes",
        "year": "2017",
    },
    "Ying": {
        "gender": "female",
        "role": ["front-line", "map-control"],
        "side": "attacker",
        "speed": 2,
        "country": "hong kong",
        "continent": "asia",
        "org": "sdu",
        "squad": "wolfguard",
        "year": "2017",
    },
    "Jackal": {
        "gender": "male",
        "role": ["intel", "map-control"],
        "side": "attacker",
        "speed": 2,
        "country": "spain",
        "continent": "europe",
        "org": "geo",
        "squad": "viperstrike",
        "year": "2017",
    },
    "Hibana": {
        "gender": "female",
        "role": ["breach", "front-line"],
        "side": "attacker",
        "speed": 3,
        "country": "japan",
        "continent": "asia",
        "org": "sat",
        "squad": "viperstrike",
        "year": "2016",
    },
    "Capitao": {
        "gender": "male",
        "role": ["front-line", "map-control"],
        "side": "attacker",
        "speed": 3,
        "country": "brazil",
        "continent": "south america",
        "org": "bope",
        "squad": "viperstrike",
        "year": "2016",
    },
    "Blackbeard": {
        "gender": "male",
        "role": ["breach", "front-line"],
        "side": "attacker",
        "speed": 1,
        "country": "usa",
        "continent": "north america",
        "org": "navy seal",
        "squad": "redhammer",
        "year": "2016",
    },
    "Buck": {
        "gender": "male",
        "role": ["breach", "support"],
        "side": "attacker",
        "speed": 2,
        "country": "canada",
        "continent": "north america",
        "org": "jtf2",
        "squad": "redhammer",
        "year": "2016",
    },
    "Sledge": {
        "gender": "male",
        "role": ["breach", "anti-gadget"],
        "side": "attacker",
        "speed": 2,
        "country": "scotland",
        "continent": "europe",
        "org": "sas",
        "squad": "redhammer",
        "year": "2015",
    },
    "Thatcher": {
        "gender": "male",
        "role": ["anti-gadget", "support"],
        "side": "attacker",
        "speed": 1,
        "country": "england",
        "continent": "europe",
        "org": "sas",
        "squad": "viperstrike",
        "year": "2015",
    },
    "Ash": {
        "gender": "female",
        "role": ["breach", "front-line"],
        "side": "attacker",
        "speed": 3,
        "country": "israel",
        "continent": "asia",
        "org": "fbi swat",
        "squad": "redhammer",
        "year": "2015",
    },
    "Thermite": {
        "gender": "male",
        "role": ["breach", "support"],
        "side": "attacker",
        "speed": 2,
        "country": "usa",
        "continent": "north america",
        "org": "fbi swat",
        "squad": "redhammer",
        "year": "2015",
    },
    "Montagne": {
        "gender": "male",
        "role": ["intel", "support"],
        "side": "attacker",
        "speed": 1,
        "country": "france",
        "continent": "europe",
        "org": "gign",
        "squad": "wolfguard",
        "year": "2015",
    },
    "Twitch": {
        "gender": "female",
        "role": ["intel", "anti-gadget"],
        "side": "attacker",
        "speed": 2,
        "country": "france",
        "continent": "europe",
        "org": "gign",
        "squad": "wolfguard",
        "year": "2015",
    },
    "Blitz": {
        "gender": "male",
        "role": ["front-line", "map-control"],
        "side": "attacker",
        "speed": 2,
        "country": "germany",
        "continent": "europe",
        "org": "gsg 9",
        "squad": "viperstrike",
        "year": "2015",
    },
    "IQ": {
        "gender": "female",
        "role": ["intel", "support"],
        "side": "attacker",
        "speed": 3,
        "country": "germany",
        "continent": "europe",
        "org": "gsg 9",
        "squad": "nighthaven",
        "year": "2015",
    },
    "Fuze": {
        "gender": "male",
        "role": ["anti-gadget"],
        "side": "attacker",
        "speed": 1,
        "country": "uzbekistan",
        "continent": "asia",
        "org": "spetsnaz",
        "squad": "redhammer",
        "year": "2015",
    },
    "Glaz": {
        "gender": "male",
        "role": ["intel", "support"],
        "side": "attacker",
        "speed": 3,
        "country": "russia",
        "continent": "europe",
        "org": "spetsnaz",
        "squad": "ghosteyes",
        "year": "2015",
    },
}

OPERATORS = ATTACKERS | DEFENDERS

if __name__ == "__main__":
    continents_seen = []
    for op in OPERATORS.keys():
        if (len(OPERATORS[op]["role"])) not in continents_seen:
            continents_seen.append(len(OPERATORS[op]["role"]))

    print(continents_seen)